cjapps/user/urls.py
from django.urls import path, include
from . import views

from django.contrib.auth.views import (
    # PasswordResetView,
    # PasswordResetDoneView,
    # PasswordResetConfirmView,
    # PasswordResetCompleteView,
    LoginView
)

urlpatterns = [
    path('', views.homepage_view, name='homepage'),
    path('user/', include('django.contrib.auth.urls')),
    path('user/login/', LoginView.as_view(), name='login'),
    # path('user/signup/', views.signup_view, name='signup'),
    path("user/register/", views.register_view, name="register"),
    path('user/verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),

    path('user/verify-email/', views.verify_email, name='verify-email'),
    path('user/verify-email/done/', views.verify_email_done, name='verify-email-done'),
    path('user/verify-email/complete/', views.verify_email_complete, name='verify-email-complete'),

    path("user/dashboard/", views.dashboard_view, name="dashboard"),
    path("user/profile/", views.profile_view, name="profile"),
    path("user/profile/edit/", views.profile_edit_view, name="edit_profile"),
    path("user/profile/<int:id>", views.profile_single_view, name="profile_single"),
    path("user/password/change/", views.change_password_view, name="password_change"),

    path("user/list/", views.UserListView.as_view(), name="user_list"),
    path("user/add/", views.user_add_view, name="user_add"),
    path("user/<int:pk>/edit/", views.user_edit_view, name="user_edit"),
    path("user/<int:pk>/delete/", views.user_delete_view, name="user_delete"),

    path("group/list/", views.GroupListView.as_view(), name="group_list"),
    path("group/<int:pk>/edit/", views.group_desc_edit_view, name="group_edit"),

    path("user/import/", views.user_import_view, name="user_import"), #views.ImportUserView.as_view()
]

cjproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.conf.urls import url
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cjapp.urls')),
    path('', include('user.urls')),
    path('', include('counselling.urls')),
    path('', include('training.urls')),
    path('', include('question_bank.urls')),
    path('', include('assessment.urls')),
    # url('^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('reports/', include('reports.urls', namespace='reports')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cjapps/user/models.py
# from django.contrib.auth.models import AbstractUser
# from django.utils.translation import gettext_lazy as _
# from django.contrib.auth.base_user import BaseUserManager

from django.db import models
from django.db.models import Q
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.urls import reverse
from django.conf import settings
from PIL import Image
from django.utils.translation import gettext_lazy as _

from django.contrib.auth.models import Group
# from django_group_model.models import AbstractGroup


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)
        extra_fields.setdefault('role', User.CJ_ADMIN)
        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)
    
    def search(self, query=None):
        queryset = self.get_queryset()
        if query is not None:
            or_lookup = (
                Q(username__icontains=query)
                | Q(first_name__icontains=query)
                | Q(last_name__icontains=query)
                | Q(email__icontains=query)
            )
            queryset = queryset.filter(
                or_lookup
            ).distinct()  # distinct() is often necessary with Q lookups
        return queryset
    
    # def get_student_count(self):
    #     return self.model.objects.filter(is_student=True).count()
    # def get_lecturer_count(self):
    #     return self.model.objects.filter(is_lecturer=True).count()
    # def get_superuser_count(self):
    #     return self.model.objects.filter(is_superuser=True).count()

class User(AbstractUser):

    GENDERS = (("M", "Male"), ("F", "Female"), ("O", "Others"))
    OCCUPATION = (("employed", "Employed"), 
        ("self-employed", "Self Employed"), 
        ("job-seek-fresher", "Job seeking-Fresher"),
        ("job-seek-nonfresher", "Job seeking-nonFresher"),
        ("college-student", "College Student"), 
        ("school-student", "School Student"))
    EDUCATION_LEVEL = (("below-plus2", "5-12"),
        ("under-grad", "Undergraduate"), 
        ("post-grad", "Post Graduate"),
        ("mphil", "M-Phil"),
        ("phd", "PhD"))
    OCCUPATION_MAJOR = ((1, "Employed"), (2, "Self Employed"), (3, "Retired"))

    # SUPER_ADMIN = '0'         # Super Admin
    CJ_ADMIN = '1'              # CJ Admin
    CORPORATE_ADMIN = '2'       # Corporate Admin
    CORPORATE_EXCLUSIVE = '3'   # Corporate Exclusive
    PSYCHOMETRICIAN = '4'       # Psychometrician
    SME = '5'                   # SME
    REVIEWER = '6'              # Reviewer
    TRAINER = '7'               # Trainer
    GROUP_ADMIN = '8'           # Group admins
    COUNSELLOR = '9'            # Counsellor
    INDIVIDUAL = '10'           # Individuals
    CHANNEL_PARTNER = '11'      # Channel Partner
    CORPORATE_INDIVIDUAL = '12' # Corporate Individual
    CJ_MANGER = '13'            # CJ Manager
    HELPDESK = '14'             # Helpdesk


    DEFAULT_USER = '9'
    
    ROLES = { 
        # SUPER_ADMIN: 'Super User', 
        CJ_ADMIN: 'CareerJudge Admin', 
        CORPORATE_ADMIN: 'Corporate Admin', 
        CORPORATE_EXCLUSIVE: 'Corporate Exclusive',
        PSYCHOMETRICIAN: 'Psychometrician',
        SME: 'SME',
        REVIEWER: 'Reviewer',
        TRAINER: 'Trainer',
        GROUP_ADMIN: 'Group Admin',
        COUNSELLOR: 'Counsellor',
        INDIVIDUAL: 'Individual',
        CHANNEL_PARTNER: 'Channel Partner',
        CORPORATE_INDIVIDUAL: 'Corporate Individual',
        CJ_MANGER: 'CJ Manager',
        HELPDESK: 'Helpdesk',
    }

    # use email instead of username 
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    username = None
    email = models.EmailField(_('Email Address'), max_length=50, unique=True)
    email_is_verified = models.BooleanField(_('Email Verified'), default=False)
    #------------------------------

    role = models.CharField(_('User Role'), default=DEFAULT_USER, choices=ROLES, max_length=10) 
    
    # groups = models.ManyToManyField(
    #     settings.AUTH_GROUP_MODEL,
    #     verbose_name=_("groups"),
    #     blank=True,
    #     help_text=_(
    #         "The groups this user belongs to. A user will get all permissions "
    #         "granted to each of their groups."
    #     ),
    #     related_name="user_set",
    #     related_query_name="user",

    # )

    # individual profile fields 
    first_name = models.CharField(_('First Name'), max_length=100, blank=True, null=True)
    middle_name = models.CharField(_('Middle Name'), max_length=100, blank=True, null=True)
    last_name = models.CharField(_('Last Name'), max_length=100, blank=True, null=True)

    gender = models.CharField(_('Gender'), max_length=1, choices=GENDERS, blank=True, null=True)
    dob = models.DateField(_('Date of Birth'), blank=True, null=True)
    phone = models.CharField(_('Phone'), max_length=60, blank=True, null=True)
    
    occupation = models.CharField(_('Occupation'), max_length=100, choices=OCCUPATION, blank=True, null=True)
    cur_position = models.CharField(_('Current Position'), max_length=50, blank=True, null=True)
    work_exp = models.IntegerField(_('Work Experience'), blank=True, null=True)
    
    high_education = models.CharField(_('Highest Education'), max_length=50, blank=True, null=True)
    edu_level = models.CharField(_('Education Level'), max_length=50, choices=EDUCATION_LEVEL, blank=True, null=True)
    institution_name = models.CharField(_('Institution Name'), max_length=50, blank=True, null=True)
    institution_place = models.CharField(_('Place of Institution'), max_length=50, blank=True, null=True)
    
    country = models.CharField(_('Country of Origin'), max_length=50, blank=True, null=True)
    state = models.CharField(_('State/Province'), max_length=50, blank=True, null=True)
    location = models.CharField(_('Location'), max_length=50, blank=True, null=True)
    
    assess_pack_alloc = models.CharField(_('Assessment Package allocated'), max_length=100, blank=True, null=True)
  
    picture = models.ImageField(
        upload_to="profile_pictures/%y/%m/%d/", default="default.png", blank=True, null=True
    )

    # corporate profile fields
    org_name = models.CharField(_('Organization Name'), max_length=100, blank=True, null=True)
    manager_name = models.CharField(_('Manager Name'), max_length=100, blank=True, null=True)
    # phone = models.CharField(max_length=60, blank=True, null=True)
    group_name = models.CharField(_('Group Name'), max_length=100, blank=True, null=True)
    pan_tan = models.CharField(_('PAN/TAN'), max_length=60, blank=True, null=True)
    off_address = models.CharField(_('Office Address'), max_length=100, blank=True, null=True)

    # group admins
    emp_id = models.CharField(_('Employee ID'), max_length=100, blank=True, null=True)
    div_region = models.CharField(_('Division/Region'), max_length=100, blank=True, null=True)
    ga_permissions = models.CharField(_('Permissions Allotted'), max_length=100, blank=True, null=True)

    # reviewer / trainer / councellor profile fields

    pan = models.CharField(_('PAN Number'), max_length=50, blank=True, null=True)
    bank_ac = models.CharField(_('Bank Account Number'), max_length=50, blank=True, null=True)
    bank_name = models.CharField(_('Bank Name'), max_length=50, blank=True, null=True)
    bank_branch = models.CharField(_('Bank Branch'), max_length=50, blank=True, null=True)
    bank_ifsc = models.CharField(_('Bank IFSC'), max_length=50, blank=True, null=True)

    contact_address = models.CharField(_('Contact Address'), max_length=255, blank=True, null=True)
    perm_address = models.CharField(_('Permanent Address'), max_length=255, blank=True, null=True)
    
    domain_exp = models.IntegerField(_('Domain Experience'), blank=True, null=True)
    user_bio = models.CharField(_('User Biodata'), max_length=500, blank=True, null=True)

    # channel partner profile fields 
    chp_agency_name = models.CharField(_('Agency Name'), max_length=100, blank=True, null=True)
    chp_agrmt_id = models.CharField(_('Channel Partner Agreement ID'), max_length=100, blank=True, null=True)
    chp_contr_period = models.CharField(_('Contract Period'), max_length=100, blank=True, null=True)
    chp_region = models.CharField(_('Region Allocated'), max_length=100, blank=True, null=True)
    
    # ----------------------------------

    createdby = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True
    )

    rate = models.TextField(blank=True, null=True)
    category = models.TextField(blank=True, null=True)

    @property
    def get_full_name(self):
        full_name = self.email
        if self.first_name and self.last_name and self.middle_name:
            full_name = self.first_name + " " + self.middle_name + " " + self.last_name
        elif self.first_name and self.last_name:
            full_name = self.first_name + " " + self.last_name
        return full_name
    
    # def __str__(self):
    #     return "{} ({})".format(self.get_full_name, self.email)

    @property
    def is_cjadmin(self):
        return True if self.role == '1' else False
    @property
    def is_corpadmin(self):

cjapps/user/templates/user/_verify_email.html
<h1>You need to verify your email</h1>
<form method="post">
    {% csrf_token %}
    <input class="btn btn-primary max-btn" type="submit" value="Verify">
</form>

cjapps/user/templates/user/group_list.html
{% extends 'base.html' %}
{% block title %}{{ title }} | Career Judge{% endblock title %}

{% block content %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item active" aria-current="page">Users</li>
    </ol>
</nav>

<!-- <div id="input-nav"><a href="{#% url 'home' %#}" class="primary1">Home</a> Users</div> -->

{% if request.user.is_superuser %}
<!-- <div class="manage-wrap">
    <a class="btn btn-sm btn-primary" href="{% url 'user_add' %}"><i class="fas fa-plus"></i> Add User</a>
</div> -->
{% endif %}

<div class="title-1"><i class="fa fa-users"></i>Roles</div>

{% include 'snippets/messages.html' %}
{#% include 'snippets/filter_form.html' %#}

<div class="table-responsive table-shadow table-light table-striped m-0 mt-3">
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th> Name </th>
                <th> Description </th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            
            {% for group in object_list  %}
            <tr>
                <td> {{ forloop.counter }}.</td>
                <td>{{ group.name }}</td>
                <td>{{ group.desc }}</td>
                <!-- <td><a class="btn btn-primary text-light m-auto" href="/admin/auth/group/{{ group.id }}/change">Update Permissions</a></td> -->                
                <td>
                    {% if perms.auth.change_group %}
                    <div class="dropdown">
                        <button class="btn btn-sm" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-ellipsis-vertical"></i>
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="/group/{{ group.id }}/edit"><i class="fas fa-edit"></i> Update Description</a></li>
                            <li><a class="dropdown-item" href="/admin/auth/group/{{ group.id }}/change"><i class="fas fa-edit"></i> Update Permissions</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </td>

                {% empty %}
                <tr>
                  <td colspan="6">
                  <span class="text-danger">
                    No User.
                    {% if request.user.is_superuser %}
                    <a href="{% url 'user_add' %}">
                    <i class="primary" style="font-size: 22px;">
                       Add User Now.
                    </i>
                    {% endif %}
                    </a>
                  </span>
                </td>
                </tr>

            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="pagination mb-4">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock content %}

cjapps/user/templates/user/profile.html
{% extends 'base.html' %}
{% block title %} {{ title }} | Career Judge{% endblock title %}

{% load static %}
{% load i18n %}

{% block content %}

{% if user.is_authenticated %}

<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <!-- <li class="breadcrumb-item"><a href="{% url 'user_list' %}">Users</a></li> -->
      <li class="breadcrumb-item active" aria-current="page">{{ user.get_full_name }}</li>
    </ol>
</nav>
{% include 'snippets/messages.html' %}
<div class="row">
    <div class="col-md-3 mx-auto">
        <div class="card  p-2">
            <div class="text-center">
                <img src="{{ user.picture.url }}" class="w-100">
                <ul class="px-2 list-unstyled">
                    <li>{{ user.get_full_name|title }}</li>
                    <li><strong>Last login: </strong>{{ user.last_login|date }}</li>
                    <li><strong>Role: </strong>{{ user.get_user_role }}</li>
                </ul>
            </div>
            <hr>
            <a class="mb-2" href="{% url 'edit_profile' %}"><i class="fas fa-user-edit"></i>
                <span class="mobile-hide">Edit Profile</span></a>
            <a href="{% url 'password_change' %}"><i class="fas fa-lock"></i><span class="mobile-hide">
                    Change password</span></a>
        </div>
    </div>

    <div class="col-md-9 mx-auto">
        <div class="card">
            <div class="card-body">
                <p class="fw-bold"><i class="fas fa-user"></i> Profile Information</p>
                <div class="profile-info">
                    <p><strong>Full Name:</strong> {{ user.get_full_name|title }}</p>
                    {% if user.is_individual or user.is_psychometrician or user.is_reviewer or user.is_trainer or user.is_counsellor %}
                    <p><strong>Gender:</strong> {{ user.get_gender_display }}</p>
                    <p><strong>Date of Birth:</strong> {{ user.dob }}</p>
                    <p><strong>State/Province: </strong>{{ user.state }}</p>
                    <p><strong>Country of Origin: </strong>{{ user.country }}</p>
                    <p><strong>Occupation: </strong>{{ user.get_occupation_display }}</p>
                    <p><strong>Current Position: </strong>{{ user.cur_position }}</p>
                    <p><strong>Work Experience: </strong>{{ user.work_exp }}</p>
                    <p><strong>Highest Education: </strong>{{ user.high_education }}</p>
                    {% endif %}
                    {% if user.is_individual %}
                    <p><strong>Education Level: </strong>{{ user.get_edu_level_display }}</p>
                    <p><strong>Institution Name: </strong>{{ user.institution_name }}</p>
                    <p><strong>Place of Institution: </strong>{{ user.institution_place }}</p>
                    <p><strong>Location: </strong>{{ user.location }}</p>
                    <p><strong>Assessment Package allocated: </strong>{{ user.assess_pack_alloc }}</p>
                    {% endif %}
                    {% if user.is_corpadmin or user.is_corpexclusive %}
                    <p><strong>Group name:</strong> {{ user.group_name }}</p>
                    <p><strong>Organization Name:</strong> {{ user.org_name }}</p>
                    <p><strong>Manager name:</strong> {{ user.manager_name }}</p>
                    <p><strong>PAN/TAN:</strong> {{ user.pan_tan }}</p>
                    {% endif %}
                    {% if user.is_psychometrician or user.is_reviewer or user.is_trainer or user.is_counsellor or user.is_channelpartner %}
                    <p><strong>PAN:</strong> {{ user.pan }}</p>
                    <p><strong>Bank Account Number:</strong> {{ user.bank_ac }}</p>
                    <p><strong>Bank Name:</strong> {{ user.bank_name }}</p>
                    <p><strong>Bank Branch:</strong> {{ user.bank_branch }}</p>
                    <p><strong>IFSC Code:</strong> {{ user.bank_ifsc }}</p>
                    {% endif %}
                    {% if user.is_reviewer or user.is_trainer or user.is_counsellor %}
                    <p><strong>Domain Experience:</strong> {{ user.domain_exp }}</p>
                    <p><strong>Bio:</strong> {{ user.user_bio }}</p>
                    {% endif %}
                    {% if user.is_channelpartner %}
                    <p><strong>Agency Name:</strong> {{ user.chp_agency_name }}</p>
                    <p><strong>Agreement ID:</strong> {{ user.chp_agrmt_id }}</p>
                    <p><strong>Contract Period:</strong> {{ user.chp_contr_period }}</p>
                    <p><strong>Region Allocated:</strong> {{ user.chp_region }}</p>
                    {% endif %}
                </div>    
                <hr>
                <p class="fw-bold"><i class="fas fa-phone-square-alt"></i> Contact Information</p>
                <div class="contact-info">
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    <p><strong>Phone:</strong> {{ user.phone }}</p>
                    {% if user.is_psychometrician or user.is_reviewer or user.is_trainer or user.is_counsellor %}
                    <p><strong>Contact Address:</strong> {{ user.contact_address }}</p>
                    <p><strong>Permanent Address:</strong> {{ user.perm_address }}</p>
                    {% elif user.is_corpadmin or user.is_corpexclusive %}
                    <p><strong>Office Address:</strong> {{ user.off_address }}</p>
                    {% endif %}
                </div>
    
                <hr>
                <p class="fw-bold"><i class="fa fa-calendar-day"></i> Important Dates</p>
                <div class="dashboard-description">
                    <p><strong>Last login:</strong> {{ user.last_login }}</p>
                    <p><strong>Registered Date:</strong> {{ user.date_joined|date }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-3 mx-auto"></div>

</div>
{% endif %}

{% endblock content %}

cjapps/user/templates/user/profile_single.html
{% extends 'base.html' %}
{% block title %} {{ title }} | Career Judge{% endblock title %}

{% load static %}
{% load i18n %}

{% block content %}

{% if user.is_authenticated %}

<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="/">Home</a></li>
      <li class="breadcrumb-item"><a href="{% url 'user_list' %}">Users</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ user.get_full_name }}</li>
    </ol>
</nav>
{% include 'snippets/messages.html' %}
<div class="row">
    <div class="col-md-3 mx-auto">
        <div class="card  p-2">
            <div class="text-center">
                <img src="{{ user.picture.url }}" class="w-100">
                <ul class="px-2 list-unstyled">
                    <li>{{ user.get_full_name|title }}</li>
                    <li><strong>Last login: </strong>{{ user.last_login|date }}</li>
                    <li><strong>Role: </strong>{{ user.get_user_role }}</li>
                </ul>
            </div>
            <hr>
            {#% if user.is_superuser %#}
            <div class="btn-flex">
                {% if user.is_superuser %}
                <a class="edit-btn" href="{% url 'user_edit' pk=user.id %}">
                    <i class="fas fa-user-edit"></i><span class="mobile-hide">Edit Profile</span>
                </a>
                {% endif %}
                {#% if user.is_lecturer %#}
                <!-- <a class="edit-btn" href="{#% url 'staff_edit' pk=user.id %#}">
                    <i class="fas fa-user-edit"></i><span class="mobile-hide">Edit Profile</span>
                </a> -->
                {#% endif %#}
            </div>
            {#% endif %#}
        </div>
    </div>

    <div class="col-md-9 mx-auto">
        <div class="card">
            <div class="card-body">
                <p class="fw-bold"><i class="fas fa-user"></i> Profile Information</p>
                <div class="profile-info">
                    <p><strong>Full Name:</strong> {{ user.get_full_name|title }}</p>
                    {% if user.is_corpindividual %}
                    <p><strong>Gender:</strong> {{ user.get_gender_display }}</p>
                    <p><strong>Date of Birth:</strong> {{ user.dob }}</p>
                    {% endif %}
                    {% if user.is_individual or user.is_psychometrician or user.is_reviewer or user.is_trainer or user.is_counsellor %}
                    <p><strong>Gender:</strong> {{ user.get_gender_display }}</p>
                    <p><strong>Date of Birth:</strong> {{ user.dob }}</p>
                    <p><strong>State/Province: </strong>{{ user.state }}</p>
                    <p><strong>Country of Origin: </strong>{{ user.country }}</p>
                    <p><strong>Occupation: </strong>{{ user.get_occupation_display }}</p>
                    <p><strong>Current Position: </strong>{{ user.cur_position }}</p>
                    <p><strong>Work Experience: </strong>{{ user.work_exp }}</p>
                    <p><strong>Highest Education: </strong>{{ user.high_education }}</p>
                    {% endif %}
                    {% if user.is_individual %}
                    <p><strong>Education Level: </strong>{{ user.get_edu_level_display }}</p>
                    <p><strong>Institution Name: </strong>{{ user.institution_name }}</p>
                    <p><strong>Place of Institution: </strong>{{ user.institution_place }}</p>
                    <p><strong>Location: </strong>{{ user.location }}</p>
                    <p><strong>Assessment Package allocated: </strong>{{ user.assess_pack_alloc }}</p>
                    {% endif %}
                    {% if user.is_corpadmin or user.is_corpexclusive %}
                    <p><strong>Group name:</strong> {{ user.group_name }}</p>
                    <p><strong>Organization Name:</strong> {{ user.org_name }}</p>
                    <p><strong>Manager name:</strong> {{ user.manager_name }}</p>
                    <p><strong>PAN/TAN:</strong> {{ user.pan_tan }}</p>
                    {% endif %}
                    {% if user.is_psychometrician or user.is_reviewer or user.is_trainer or user.is_counsellor or user.is_channelpartner %}
                    <p><strong>PAN:</strong> {{ user.pan }}</p>
                    <p><strong>Bank Account Number:</strong> {{ user.bank_ac }}</p>
                    <p><strong>Bank Name:</strong> {{ user.bank_name }}</p>
                    <p><strong>Bank Branch:</strong> {{ user.bank_branch }}</p>
                    <p><strong>IFSC Code:</strong> {{ user.bank_ifsc }}</p>
                    {% endif %}
                    {% if user.is_reviewer or user.is_trainer or user.is_counsellor %}
                    <p><strong>Domain Experience:</strong> {{ user.domain_exp }}</p>
                    <p><strong>Bio:</strong> {{ user.user_bio }}</p>
                    {% endif %}
                    {% if user.is_channelpartner %}
                    <p><strong>Agency Name:</strong> {{ user.chp_agency_name }}</p>
                    <p><strong>Agreement ID:</strong> {{ user.chp_agrmt_id }}</p>
                    <p><strong>Contract Period:</strong> {{ user.chp_contr_period }}</p>
                    <p><strong>Region Allocated:</strong> {{ user.chp_region }}</p>
                    {% endif %}
                </div>
                <hr>
                <p class="fw-bold"><i class="fas fa-phone-square-alt"></i> Contact Info</p>
                <div class="contact-info">
                    <p><strong>Email:</strong> {{ user.email }}</p>
                    <p><strong>Phone:</strong> {{ user.phone }}</p>
                    {% if user.is_psychometrician or user.is_reviewer or user.is_trainer or user.is_counsellor %}
                    <p><strong>Contact Address:</strong> {{ user.contact_address }}</p>
                    <p><strong>Permanent Address:</strong> {{ user.perm_address }}</p>
                    {% elif user.is_corpadmin or user.is_corpexclusive %}
                    <p><strong>Office Address:</strong> {{ user.off_address }}</p>
                    {% endif %}
                </div>
    
                <hr>
                <p class="fw-bold"><i class="fa fa-calendar-day"></i> Important Dates</p>
                <div class="dashboard-description">
                    <p><strong>Last login:</strong> {{ user.last_login }}</p>
                    <p><strong>Registered Date:</strong> {{ user.date_joined|date }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-3 mx-auto"></div>

</div>
{% endif %}

{% endblock content %}

cjapps/user/templates/user/verify_email_done.html
<h3>An email has been sent with instructions to verify your email</h3>